#!/usr/bin/python3

import apt
import random

cache = apt.Cache()

descs = {}
for pkg in cache:
    ver = pkg.candidate
    if ver is None: continue
    tags = ver.record.get("Tag", None)
    if tags is None or "role::program" not in tags: continue
    descs[pkg.shortname] = ver.summary

names = list(descs.keys())
cand_idx = random.randint(0, len(names))
name = names.pop(cand_idx)
other_names = random.sample(names, 2)
cand_descs = [descs[name]] + [descs[x] for x in other_names]
random.shuffle(cand_descs)
print(name)
count = 0
for d in cand_descs:
    count = count + 1
    print("   ",count, d)
useranswer = 0
while useranswer - 1 not in range(count):
    text = input("Which description matches the package name?")
    if text in [str(i) for i in range(1,count+1)]:
        useranswer = int(text)
if cand_descs[useranswer-1] == descs[name]:
    print("Correct!")
else:
    print("Incorrect!")
